services:
  mysql:
    container_name: sqlserver
    image: mysql
    ports:
      - 3306:3306
    networks:
      - customer_network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=customer
  customer_app:
    depends_on:
      - mysql
    container_name: customer-api
    image: aryoadi/customer-app
    ports:
      - 8080:8080
    networks:
      - customer_network
    environment:
      - jwt_secret=veryLongAndSecureKey123456789lalalala
      - HOST=sqlserver
networks:
  customer_network:
    name: customer_network
